runtime: nodejs10
instance_class: F2
handlers:
- url: /.*
  script: true
  secure: always
  redirect_http_response_code: 301

# [START gae_analytics_env_variables]
#env_variables:
#  GA_TRACKING_ID: YOUR_TRACKING_ID
# [END gae_analytics_env_variables]